envs:
  env: FrozenLake

alg:
  gamma: 0.9
  lr: 0.05
  policy_accuracy: 1e-10
  UVIP_accuracy: 1e-5
  debug: True
  save_path_reinforce: plots/out_reinforce.png
  save_path_scores: plots/out_scores.png
  save_path_UVIP: plots/out_UVIP.png

FrozenLake:
  max_steps: 30
  seed: 42

Chain:
  seed: 42